
export function factoryHeaders() {
    return {
        'Accept': "application/json",
        'X-Correlation-ID': crypto.randomUUID(),
        'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjRVQzhiOVJFZl83cVlkUDRWUV9JeSJ9.eyJpc3MiOiJodHRwczovL2Rldi1lMWRyN3RlZTVxOGNxZ3prLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJkTHlOTkVwTnlsZzBRcWtiYkl5azJOM1dNWW5TQTN3cEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly90YXhpLXNlcnZpY2UtYXBpIiwiaWF0IjoxNzcwMjAyOTE4LCJleHAiOjE3NzAyODkzMTgsInNjb3BlIjoidXNlcjpyZWFkIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiZEx5Tk5FcE55bGcwUXFrYmJJeWsyTjNXTVluU0Ezd3AifQ.AZ9TGu3y7KqOuSl7FoHpjlRheUT4cORO7wqlHQsYd_d0vj0MGr_4MD7KlkYO1eUi8VwZjRWY5Q-wjIjYJYkDMNalTuVUHBMBC29fPJ-HMxmcuLpCbUjHhxhgi4za2sYmm7SdTtAzo1GjWMeV9dQeQsOLaicZl-qlo0N_mS4E1FDgAr7PQY3QJJmO68NRtCDZ-2PWxXCXSCcpOzVWjav93AvZkxKoVgK85fW7YAMJpfrY46Fqraf7kbKUzx5tWSPVrviciC2TwHKEtYAB1USdMBwu2qCsuqgSWupfeUZ78Cv-VVVxAx5ynqFY2uhERAYIFwkNIROVV08FTZZnSZK98A'
    };
}