export function factoryHeaders() {
    return {
        'Content-Type': 'application/json',
        'X-Correlation-ID': crypto.randomUUID(),
        'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjRVQzhiOVJFZl83cVlkUDRWUV9JeSJ9.eyJpc3MiOiJodHRwczovL2Rldi1lMWRyN3RlZTVxOGNxZ3prLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJkTHlOTkVwTnlsZzBRcWtiYkl5azJOM1dNWW5TQTN3cEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly90YXhpLXNlcnZpY2UtYXBpIiwiaWF0IjoxNzY2NzQ0MjkxLCJleHAiOjE3NjY4MzA2OTEsInNjb3BlIjoidXNlcjpyZWFkIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiZEx5Tk5FcE55bGcwUXFrYmJJeWsyTjNXTVluU0Ezd3AifQ.I0Aj4wK7yDpDsIcmGK1pr9edPPX2uppeDD14fNZx83pn-YKn3BvojzV3VIUX_bld4Q3KYWzDKvFmBfKrYZUNoUTXU7BFs9KB5Ps1g6ZGEOEG_vp84eLNVO_kIZFMySzgPP1WE1nYRDMMljAlYctS0So2uKlg0KKOsVYNUVlsV--bqd6ehXhEvQDMXCFFHriaXo6YxAmH9dzDWrgBZj2YKXA4w8cg2jF7oYLkVBVf_zZqEGAVwG3KbQ3nllsCSkfbR8N8fQPhkWgbh7_47FfjVRH3K5hJ2VtqntSJIhzMa__v3TmEWvcANugoThfvz7ORfmqaRTXwjEmcAxXVw66csg'
    };
}