services:
  api:
    image: url-shortener-api-dev:latest
    restart: unless-stopped
    build:
      context: ../../src
      dockerfile: ./Dockerfile.Development
    env_file:
      - .env
    networks:
      - url-shortener-service-dev-public
    ports:
      - "127.0.0.1:8085:8080"
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "1m"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
          pids: 100
        reservations:
          cpus: '1'
          memory: '512M'

networks:
  url-shortener-service-dev-public:
    driver: bridge