# =====================================================
# Build + Publish
# =====================================================
FROM mcr.microsoft.com/dotnet/sdk:11.0-preview-noble AS publish

WORKDIR /src

COPY ./main/Api/Api.csproj ./main/Api/
COPY ./main/Application/Application.csproj ./main/Application/
COPY ./main/Domain/Domain.csproj ./main/Domain/
COPY ./main/Infrastructure/Infrastructure.csproj ./main/Infrastructure/
COPY ./main/CrossCutting/CrossCutting.csproj ./main/CrossCutting/
COPY *.sln ./
COPY nuget.config ./
COPY Directory.Build.props ./
COPY Directory.Packages.props ./

RUN dotnet restore ./main/Api/Api.csproj

COPY . .

RUN dotnet publish ./main/Api/Api.csproj \
    -c Release \
    --no-restore \
    --output /publish

# =====================================================
# Etapa Final: Imagem de Runtime
# =====================================================
FROM jacksonveroneze/aspnet:11.0-ubuntu-noble-chiseled-extra-latest AS runtime

COPY --from=publish /publish .

ENTRYPOINT ["dotnet", "Api.dll"]
